// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(WysiwygComposerFFI)
import WysiwygComposerFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_uniffi_wysiwyg_composer_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_uniffi_wysiwyg_composer_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureUniffiWysiwygComposerInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ComposerModelProtocol: AnyObject, Sendable {
    
    func actionStates()  -> [ComposerAction: ActionState]
    
    func backspace() throws -> ComposerUpdate
    
    func bold() throws -> ComposerUpdate
    
    func clear() throws -> ComposerUpdate
    
    func codeBlock() throws -> ComposerUpdate
    
    /**
     * Force a panic for test purposes
     */
    func debugPanic() 
    
    func delete() throws -> ComposerUpdate
    
    func deleteIn(start: UInt32, end: UInt32) throws -> ComposerUpdate
    
    func enter() throws -> ComposerUpdate
    
    func getContentAsHtml()  -> String
    
    func getContentAsMarkdown()  -> String
    
    func getContentAsMessageHtml()  -> String
    
    func getContentAsMessageMarkdown()  -> String
    
    func getContentAsPlainText()  -> String
    
    func getCurrentDomState()  -> ComposerState
    
    func getLinkAction()  -> LinkAction
    
    func getMentionsState()  -> MentionsState
    
    func indent() throws -> ComposerUpdate
    
    func inlineCode() throws -> ComposerUpdate
    
    /**
     * Creates an at-room mention node and inserts it into the composer at the current selection
     */
    func insertAtRoomMention() throws -> ComposerUpdate
    
    /**
     * Creates an at-room mention node and inserts it into the composer, replacing the
     * text content defined by the suggestion
     */
    func insertAtRoomMentionAtSuggestion(suggestion: SuggestionPattern) throws -> ComposerUpdate
    
    /**
     * Creates a mention node and inserts it into the composer at the current selection
     */
    func insertMention(url: String, text: String, attributes: [Attribute]) throws -> ComposerUpdate
    
    /**
     * Creates a mention node and inserts it into the composer, replacing the
     * text content defined by the suggestion
     */
    func insertMentionAtSuggestion(url: String, text: String, suggestion: SuggestionPattern, attributes: [Attribute]) throws -> ComposerUpdate
    
    func italic() throws -> ComposerUpdate
    
    func orderedList() throws -> ComposerUpdate
    
    func quote() throws -> ComposerUpdate
    
    func redo() throws -> ComposerUpdate
    
    func removeLinks() throws -> ComposerUpdate
    
    func replaceText(newText: String) throws -> ComposerUpdate
    
    func replaceTextIn(newText: String, start: UInt32, end: UInt32) throws -> ComposerUpdate
    
    func replaceTextSuggestion(newText: String, suggestion: SuggestionPattern, appendSpace: Bool) throws -> ComposerUpdate
    
    func select(startUtf16Codeunit: UInt32, endUtf16Codeunit: UInt32) throws -> ComposerUpdate
    
    func setContentFromHtml(html: String) throws  -> ComposerUpdate
    
    func setContentFromMarkdown(markdown: String) throws  -> ComposerUpdate
    
    func setCustomSuggestionPatterns(customSuggestionPatterns: [String]) 
    
    func setLink(url: String, attributes: [Attribute]) throws -> ComposerUpdate
    
    func setLinkWithText(url: String, text: String, attributes: [Attribute]) throws -> ComposerUpdate
    
    func strikeThrough() throws -> ComposerUpdate
    
    func toExampleFormat()  -> String
    
    func toTree()  -> String
    
    func underline() throws -> ComposerUpdate
    
    func undo() throws -> ComposerUpdate
    
    func unindent() throws -> ComposerUpdate
    
    func unorderedList() throws -> ComposerUpdate
    
}
open class ComposerModel: ComposerModelProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uniffi_wysiwyg_composer_fn_clone_composermodel(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uniffi_wysiwyg_composer_fn_free_composermodel(handle, $0) }
    }

    

    
open func actionStates() -> [ComposerAction: ActionState]  {
    return try!  FfiConverterDictionaryTypeComposerActionTypeActionState.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_action_states(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func backspace() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_backspace(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func bold() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_bold(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func clear() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_clear(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func codeBlock() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_code_block(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Force a panic for test purposes
     */
open func debugPanic()  {try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_debug_panic(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func delete() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_delete(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func deleteIn(start: UInt32, end: UInt32) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_delete_in(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(start),
        FfiConverterUInt32.lower(end),$0
    )
})
}
    
open func enter() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_enter(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getContentAsHtml() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_content_as_html(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getContentAsMarkdown() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_content_as_markdown(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getContentAsMessageHtml() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_content_as_message_html(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getContentAsMessageMarkdown() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_content_as_message_markdown(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getContentAsPlainText() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_content_as_plain_text(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getCurrentDomState() -> ComposerState  {
    return try!  FfiConverterTypeComposerState_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_current_dom_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getLinkAction() -> LinkAction  {
    return try!  FfiConverterTypeLinkAction_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_link_action(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getMentionsState() -> MentionsState  {
    return try!  FfiConverterTypeMentionsState_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_get_mentions_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func indent() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_indent(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func inlineCode() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_inline_code(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Creates an at-room mention node and inserts it into the composer at the current selection
     */
open func insertAtRoomMention() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_insert_at_room_mention(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Creates an at-room mention node and inserts it into the composer, replacing the
     * text content defined by the suggestion
     */
open func insertAtRoomMentionAtSuggestion(suggestion: SuggestionPattern) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_insert_at_room_mention_at_suggestion(
            self.uniffiCloneHandle(),
        FfiConverterTypeSuggestionPattern_lower(suggestion),$0
    )
})
}
    
    /**
     * Creates a mention node and inserts it into the composer at the current selection
     */
open func insertMention(url: String, text: String, attributes: [Attribute]) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_insert_mention(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(text),
        FfiConverterSequenceTypeAttribute.lower(attributes),$0
    )
})
}
    
    /**
     * Creates a mention node and inserts it into the composer, replacing the
     * text content defined by the suggestion
     */
open func insertMentionAtSuggestion(url: String, text: String, suggestion: SuggestionPattern, attributes: [Attribute]) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_insert_mention_at_suggestion(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(text),
        FfiConverterTypeSuggestionPattern_lower(suggestion),
        FfiConverterSequenceTypeAttribute.lower(attributes),$0
    )
})
}
    
open func italic() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_italic(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func orderedList() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_ordered_list(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func quote() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_quote(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func redo() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_redo(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func removeLinks() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_remove_links(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func replaceText(newText: String) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_replace_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(newText),$0
    )
})
}
    
open func replaceTextIn(newText: String, start: UInt32, end: UInt32) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_replace_text_in(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(newText),
        FfiConverterUInt32.lower(start),
        FfiConverterUInt32.lower(end),$0
    )
})
}
    
open func replaceTextSuggestion(newText: String, suggestion: SuggestionPattern, appendSpace: Bool) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_replace_text_suggestion(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(newText),
        FfiConverterTypeSuggestionPattern_lower(suggestion),
        FfiConverterBool.lower(appendSpace),$0
    )
})
}
    
open func select(startUtf16Codeunit: UInt32, endUtf16Codeunit: UInt32) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_select(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(startUtf16Codeunit),
        FfiConverterUInt32.lower(endUtf16Codeunit),$0
    )
})
}
    
open func setContentFromHtml(html: String)throws  -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCallWithError(FfiConverterTypeDomCreationError_lift) {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_set_content_from_html(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(html),$0
    )
})
}
    
open func setContentFromMarkdown(markdown: String)throws  -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCallWithError(FfiConverterTypeDomCreationError_lift) {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_set_content_from_markdown(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(markdown),$0
    )
})
}
    
open func setCustomSuggestionPatterns(customSuggestionPatterns: [String])  {try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_set_custom_suggestion_patterns(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(customSuggestionPatterns),$0
    )
}
}
    
open func setLink(url: String, attributes: [Attribute]) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_set_link(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterSequenceTypeAttribute.lower(attributes),$0
    )
})
}
    
open func setLinkWithText(url: String, text: String, attributes: [Attribute]) throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_set_link_with_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterString.lower(text),
        FfiConverterSequenceTypeAttribute.lower(attributes),$0
    )
})
}
    
open func strikeThrough() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_strike_through(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func toExampleFormat() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_to_example_format(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func toTree() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_to_tree(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func underline() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_underline(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func undo() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_undo(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func unindent() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_unindent(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func unorderedList() throws -> ComposerUpdate  {
    return try  FfiConverterTypeComposerUpdate_lift(try rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composermodel_unordered_list(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComposerModel: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ComposerModel

    public static func lift(_ handle: UInt64) throws -> ComposerModel {
        return ComposerModel(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ComposerModel) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComposerModel {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ComposerModel, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerModel_lift(_ handle: UInt64) throws -> ComposerModel {
    return try FfiConverterTypeComposerModel.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerModel_lower(_ value: ComposerModel) -> UInt64 {
    return FfiConverterTypeComposerModel.lower(value)
}






public protocol ComposerUpdateProtocol: AnyObject, Sendable {
    
    func linkAction()  -> LinkActionUpdate
    
    func menuAction()  -> MenuAction
    
    func menuState()  -> MenuState
    
    func textUpdate()  -> TextUpdate
    
}
open class ComposerUpdate: ComposerUpdateProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uniffi_wysiwyg_composer_fn_clone_composerupdate(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uniffi_wysiwyg_composer_fn_free_composerupdate(handle, $0) }
    }

    

    
open func linkAction() -> LinkActionUpdate  {
    return try!  FfiConverterTypeLinkActionUpdate_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composerupdate_link_action(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func menuAction() -> MenuAction  {
    return try!  FfiConverterTypeMenuAction_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composerupdate_menu_action(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func menuState() -> MenuState  {
    return try!  FfiConverterTypeMenuState_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composerupdate_menu_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func textUpdate() -> TextUpdate  {
    return try!  FfiConverterTypeTextUpdate_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_composerupdate_text_update(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComposerUpdate: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ComposerUpdate

    public static func lift(_ handle: UInt64) throws -> ComposerUpdate {
        return ComposerUpdate(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ComposerUpdate) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComposerUpdate {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ComposerUpdate, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerUpdate_lift(_ handle: UInt64) throws -> ComposerUpdate {
    return try FfiConverterTypeComposerUpdate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerUpdate_lower(_ value: ComposerUpdate) -> UInt64 {
    return FfiConverterTypeComposerUpdate.lower(value)
}






public protocol MentionDetectorProtocol: AnyObject, Sendable {
    
    func isMention(url: String)  -> Bool
    
}
open class MentionDetector: MentionDetectorProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uniffi_wysiwyg_composer_fn_clone_mentiondetector(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uniffi_wysiwyg_composer_fn_free_mentiondetector(handle, $0) }
    }

    

    
open func isMention(url: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_method_mentiondetector_is_mention(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMentionDetector: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MentionDetector

    public static func lift(_ handle: UInt64) throws -> MentionDetector {
        return MentionDetector(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MentionDetector) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MentionDetector {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MentionDetector, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMentionDetector_lift(_ handle: UInt64) throws -> MentionDetector {
    return try FfiConverterTypeMentionDetector.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMentionDetector_lower(_ value: MentionDetector) -> UInt64 {
    return FfiConverterTypeMentionDetector.lower(value)
}




public struct Attribute: Equatable, Hashable {
    public var key: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }

    

    
}

#if compiler(>=6)
extension Attribute: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttribute: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Attribute {
        return
            try Attribute(
                key: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Attribute, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttribute_lift(_ buf: RustBuffer) throws -> Attribute {
    return try FfiConverterTypeAttribute.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttribute_lower(_ value: Attribute) -> RustBuffer {
    return FfiConverterTypeAttribute.lower(value)
}


public struct ComposerState: Equatable, Hashable {
    public var html: [UInt16]
    public var start: UInt32
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(html: [UInt16], start: UInt32, end: UInt32) {
        self.html = html
        self.start = start
        self.end = end
    }

    

    
}

#if compiler(>=6)
extension ComposerState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComposerState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComposerState {
        return
            try ComposerState(
                html: FfiConverterSequenceUInt16.read(from: &buf), 
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ComposerState, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt16.write(value.html, into: &buf)
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerState_lift(_ buf: RustBuffer) throws -> ComposerState {
    return try FfiConverterTypeComposerState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerState_lower(_ value: ComposerState) -> RustBuffer {
    return FfiConverterTypeComposerState.lower(value)
}


public struct MentionsState: Equatable, Hashable {
    public var userIds: [String]
    public var roomIds: [String]
    public var roomAliases: [String]
    public var hasAtRoomMention: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(userIds: [String], roomIds: [String], roomAliases: [String], hasAtRoomMention: Bool) {
        self.userIds = userIds
        self.roomIds = roomIds
        self.roomAliases = roomAliases
        self.hasAtRoomMention = hasAtRoomMention
    }

    

    
}

#if compiler(>=6)
extension MentionsState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMentionsState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MentionsState {
        return
            try MentionsState(
                userIds: FfiConverterSequenceString.read(from: &buf), 
                roomIds: FfiConverterSequenceString.read(from: &buf), 
                roomAliases: FfiConverterSequenceString.read(from: &buf), 
                hasAtRoomMention: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MentionsState, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.userIds, into: &buf)
        FfiConverterSequenceString.write(value.roomIds, into: &buf)
        FfiConverterSequenceString.write(value.roomAliases, into: &buf)
        FfiConverterBool.write(value.hasAtRoomMention, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMentionsState_lift(_ buf: RustBuffer) throws -> MentionsState {
    return try FfiConverterTypeMentionsState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMentionsState_lower(_ value: MentionsState) -> RustBuffer {
    return FfiConverterTypeMentionsState.lower(value)
}


public struct SuggestionPattern: Equatable, Hashable {
    public var key: PatternKey
    public var text: String
    public var start: UInt32
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: PatternKey, text: String, start: UInt32, end: UInt32) {
        self.key = key
        self.text = text
        self.start = start
        self.end = end
    }

    

    
}

#if compiler(>=6)
extension SuggestionPattern: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuggestionPattern: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SuggestionPattern {
        return
            try SuggestionPattern(
                key: FfiConverterTypePatternKey.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SuggestionPattern, into buf: inout [UInt8]) {
        FfiConverterTypePatternKey.write(value.key, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuggestionPattern_lift(_ buf: RustBuffer) throws -> SuggestionPattern {
    return try FfiConverterTypeSuggestionPattern.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuggestionPattern_lower(_ value: SuggestionPattern) -> RustBuffer {
    return FfiConverterTypeSuggestionPattern.lower(value)
}



public enum ActionState: Equatable, Hashable {
    
    case enabled
    case reversed
    case disabled





}

#if compiler(>=6)
extension ActionState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeActionState: FfiConverterRustBuffer {
    typealias SwiftType = ActionState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ActionState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .enabled
        
        case 2: return .reversed
        
        case 3: return .disabled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ActionState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .enabled:
            writeInt(&buf, Int32(1))
        
        
        case .reversed:
            writeInt(&buf, Int32(2))
        
        
        case .disabled:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActionState_lift(_ buf: RustBuffer) throws -> ActionState {
    return try FfiConverterTypeActionState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActionState_lower(_ value: ActionState) -> RustBuffer {
    return FfiConverterTypeActionState.lower(value)
}




public enum ComposerAction: Equatable, Hashable {
    
    case bold
    case italic
    case strikeThrough
    case underline
    case inlineCode
    case link
    case undo
    case redo
    case orderedList
    case unorderedList
    case indent
    case unindent
    case codeBlock
    case quote





}

#if compiler(>=6)
extension ComposerAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComposerAction: FfiConverterRustBuffer {
    typealias SwiftType = ComposerAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComposerAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bold
        
        case 2: return .italic
        
        case 3: return .strikeThrough
        
        case 4: return .underline
        
        case 5: return .inlineCode
        
        case 6: return .link
        
        case 7: return .undo
        
        case 8: return .redo
        
        case 9: return .orderedList
        
        case 10: return .unorderedList
        
        case 11: return .indent
        
        case 12: return .unindent
        
        case 13: return .codeBlock
        
        case 14: return .quote
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ComposerAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bold:
            writeInt(&buf, Int32(1))
        
        
        case .italic:
            writeInt(&buf, Int32(2))
        
        
        case .strikeThrough:
            writeInt(&buf, Int32(3))
        
        
        case .underline:
            writeInt(&buf, Int32(4))
        
        
        case .inlineCode:
            writeInt(&buf, Int32(5))
        
        
        case .link:
            writeInt(&buf, Int32(6))
        
        
        case .undo:
            writeInt(&buf, Int32(7))
        
        
        case .redo:
            writeInt(&buf, Int32(8))
        
        
        case .orderedList:
            writeInt(&buf, Int32(9))
        
        
        case .unorderedList:
            writeInt(&buf, Int32(10))
        
        
        case .indent:
            writeInt(&buf, Int32(11))
        
        
        case .unindent:
            writeInt(&buf, Int32(12))
        
        
        case .codeBlock:
            writeInt(&buf, Int32(13))
        
        
        case .quote:
            writeInt(&buf, Int32(14))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerAction_lift(_ buf: RustBuffer) throws -> ComposerAction {
    return try FfiConverterTypeComposerAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComposerAction_lower(_ value: ComposerAction) -> RustBuffer {
    return FfiConverterTypeComposerAction.lower(value)
}



public 
enum DomCreationError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case HtmlParseError
    case MarkdownParseError

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension DomCreationError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDomCreationError: FfiConverterRustBuffer {
    typealias SwiftType = DomCreationError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DomCreationError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .HtmlParseError
        case 2: return .MarkdownParseError

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DomCreationError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .HtmlParseError:
            writeInt(&buf, Int32(1))
        
        
        case .MarkdownParseError:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDomCreationError_lift(_ buf: RustBuffer) throws -> DomCreationError {
    return try FfiConverterTypeDomCreationError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDomCreationError_lower(_ value: DomCreationError) -> RustBuffer {
    return FfiConverterTypeDomCreationError.lower(value)
}



public enum LinkAction: Equatable, Hashable {
    
    case createWithText
    case create
    case edit(url: String
    )
    case disabled





}

#if compiler(>=6)
extension LinkAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLinkAction: FfiConverterRustBuffer {
    typealias SwiftType = LinkAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LinkAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .createWithText
        
        case 2: return .create
        
        case 3: return .edit(url: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .disabled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LinkAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .createWithText:
            writeInt(&buf, Int32(1))
        
        
        case .create:
            writeInt(&buf, Int32(2))
        
        
        case let .edit(url):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(url, into: &buf)
            
        
        case .disabled:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLinkAction_lift(_ buf: RustBuffer) throws -> LinkAction {
    return try FfiConverterTypeLinkAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLinkAction_lower(_ value: LinkAction) -> RustBuffer {
    return FfiConverterTypeLinkAction.lower(value)
}




public enum LinkActionUpdate: Equatable, Hashable {
    
    case keep
    case update(linkAction: LinkAction
    )





}

#if compiler(>=6)
extension LinkActionUpdate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLinkActionUpdate: FfiConverterRustBuffer {
    typealias SwiftType = LinkActionUpdate

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LinkActionUpdate {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .keep
        
        case 2: return .update(linkAction: try FfiConverterTypeLinkAction.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LinkActionUpdate, into buf: inout [UInt8]) {
        switch value {
        
        
        case .keep:
            writeInt(&buf, Int32(1))
        
        
        case let .update(linkAction):
            writeInt(&buf, Int32(2))
            FfiConverterTypeLinkAction.write(linkAction, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLinkActionUpdate_lift(_ buf: RustBuffer) throws -> LinkActionUpdate {
    return try FfiConverterTypeLinkActionUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLinkActionUpdate_lower(_ value: LinkActionUpdate) -> RustBuffer {
    return FfiConverterTypeLinkActionUpdate.lower(value)
}




public enum MenuAction: Equatable, Hashable {
    
    case keep
    case none
    case suggestion(suggestionPattern: SuggestionPattern
    )





}

#if compiler(>=6)
extension MenuAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMenuAction: FfiConverterRustBuffer {
    typealias SwiftType = MenuAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MenuAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .keep
        
        case 2: return .none
        
        case 3: return .suggestion(suggestionPattern: try FfiConverterTypeSuggestionPattern.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MenuAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .keep:
            writeInt(&buf, Int32(1))
        
        
        case .none:
            writeInt(&buf, Int32(2))
        
        
        case let .suggestion(suggestionPattern):
            writeInt(&buf, Int32(3))
            FfiConverterTypeSuggestionPattern.write(suggestionPattern, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMenuAction_lift(_ buf: RustBuffer) throws -> MenuAction {
    return try FfiConverterTypeMenuAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMenuAction_lower(_ value: MenuAction) -> RustBuffer {
    return FfiConverterTypeMenuAction.lower(value)
}




public enum MenuState: Equatable, Hashable {
    
    case keep
    case update(actionStates: [ComposerAction: ActionState]
    )





}

#if compiler(>=6)
extension MenuState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMenuState: FfiConverterRustBuffer {
    typealias SwiftType = MenuState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MenuState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .keep
        
        case 2: return .update(actionStates: try FfiConverterDictionaryTypeComposerActionTypeActionState.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MenuState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .keep:
            writeInt(&buf, Int32(1))
        
        
        case let .update(actionStates):
            writeInt(&buf, Int32(2))
            FfiConverterDictionaryTypeComposerActionTypeActionState.write(actionStates, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMenuState_lift(_ buf: RustBuffer) throws -> MenuState {
    return try FfiConverterTypeMenuState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMenuState_lower(_ value: MenuState) -> RustBuffer {
    return FfiConverterTypeMenuState.lower(value)
}




public enum PatternKey: Equatable, Hashable {
    
    case at
    case hash
    case slash
    case custom(String
    )
    case colon





}

#if compiler(>=6)
extension PatternKey: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePatternKey: FfiConverterRustBuffer {
    typealias SwiftType = PatternKey

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PatternKey {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .at
        
        case 2: return .hash
        
        case 3: return .slash
        
        case 4: return .custom(try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .colon
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PatternKey, into buf: inout [UInt8]) {
        switch value {
        
        
        case .at:
            writeInt(&buf, Int32(1))
        
        
        case .hash:
            writeInt(&buf, Int32(2))
        
        
        case .slash:
            writeInt(&buf, Int32(3))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .colon:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatternKey_lift(_ buf: RustBuffer) throws -> PatternKey {
    return try FfiConverterTypePatternKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePatternKey_lower(_ value: PatternKey) -> RustBuffer {
    return FfiConverterTypePatternKey.lower(value)
}




public enum TextUpdate: Equatable, Hashable {
    
    case keep
    case replaceAll(replacementHtml: [UInt16], startUtf16Codeunit: UInt32, endUtf16Codeunit: UInt32
    )
    case select(startUtf16Codeunit: UInt32, endUtf16Codeunit: UInt32
    )





}

#if compiler(>=6)
extension TextUpdate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextUpdate: FfiConverterRustBuffer {
    typealias SwiftType = TextUpdate

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextUpdate {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .keep
        
        case 2: return .replaceAll(replacementHtml: try FfiConverterSequenceUInt16.read(from: &buf), startUtf16Codeunit: try FfiConverterUInt32.read(from: &buf), endUtf16Codeunit: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 3: return .select(startUtf16Codeunit: try FfiConverterUInt32.read(from: &buf), endUtf16Codeunit: try FfiConverterUInt32.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TextUpdate, into buf: inout [UInt8]) {
        switch value {
        
        
        case .keep:
            writeInt(&buf, Int32(1))
        
        
        case let .replaceAll(replacementHtml,startUtf16Codeunit,endUtf16Codeunit):
            writeInt(&buf, Int32(2))
            FfiConverterSequenceUInt16.write(replacementHtml, into: &buf)
            FfiConverterUInt32.write(startUtf16Codeunit, into: &buf)
            FfiConverterUInt32.write(endUtf16Codeunit, into: &buf)
            
        
        case let .select(startUtf16Codeunit,endUtf16Codeunit):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(startUtf16Codeunit, into: &buf)
            FfiConverterUInt32.write(endUtf16Codeunit, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextUpdate_lift(_ buf: RustBuffer) throws -> TextUpdate {
    return try FfiConverterTypeTextUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextUpdate_lower(_ value: TextUpdate) -> RustBuffer {
    return FfiConverterTypeTextUpdate.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt16: FfiConverterRustBuffer {
    typealias SwiftType = [UInt16]

    public static func write(_ value: [UInt16], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt16.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt16] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt16]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt16.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAttribute: FfiConverterRustBuffer {
    typealias SwiftType = [Attribute]

    public static func write(_ value: [Attribute], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAttribute.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Attribute] {
        let len: Int32 = try readInt(&buf)
        var seq = [Attribute]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAttribute.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryTypeComposerActionTypeActionState: FfiConverterRustBuffer {
    public static func write(_ value: [ComposerAction: ActionState], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterTypeComposerAction.write(key, into: &buf)
            FfiConverterTypeActionState.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ComposerAction: ActionState] {
        let len: Int32 = try readInt(&buf)
        var dict = [ComposerAction: ActionState]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterTypeComposerAction.read(from: &buf)
            let value = try FfiConverterTypeActionState.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
public func newComposerModel() -> ComposerModel  {
    return try!  FfiConverterTypeComposerModel_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_func_new_composer_model($0
    )
})
}
public func newMentionDetector() -> MentionDetector  {
    return try!  FfiConverterTypeMentionDetector_lift(try! rustCall() {
    uniffi_uniffi_wysiwyg_composer_fn_func_new_mention_detector($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_uniffi_wysiwyg_composer_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_func_new_composer_model() != 523) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_func_new_mention_detector() != 37103) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_action_states() != 35407) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_backspace() != 9850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_bold() != 17199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_clear() != 34939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_code_block() != 38633) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_debug_panic() != 38604) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_delete() != 51828) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_delete_in() != 43405) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_enter() != 42537) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_content_as_html() != 37608) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_content_as_markdown() != 13150) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_content_as_message_html() != 62058) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_content_as_message_markdown() != 51962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_content_as_plain_text() != 64050) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_current_dom_state() != 56950) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_link_action() != 52738) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_get_mentions_state() != 3293) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_indent() != 54702) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_inline_code() != 37901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_insert_at_room_mention() != 56029) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_insert_at_room_mention_at_suggestion() != 31318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_insert_mention() != 65522) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_insert_mention_at_suggestion() != 57118) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_italic() != 22053) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_ordered_list() != 42550) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_quote() != 54579) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_redo() != 17294) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_remove_links() != 7425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_replace_text() != 54211) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_replace_text_in() != 37194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_replace_text_suggestion() != 1869) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_select() != 23466) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_set_content_from_html() != 47789) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_set_content_from_markdown() != 41998) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_set_custom_suggestion_patterns() != 19912) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_set_link() != 32045) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_set_link_with_text() != 65518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_strike_through() != 1229) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_to_example_format() != 12847) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_to_tree() != 5802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_underline() != 33897) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_undo() != 64891) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_unindent() != 19701) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composermodel_unordered_list() != 40658) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composerupdate_link_action() != 53125) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composerupdate_menu_action() != 24041) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composerupdate_menu_state() != 21594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_composerupdate_text_update() != 63063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uniffi_wysiwyg_composer_checksum_method_mentiondetector_is_mention() != 10902) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureUniffiWysiwygComposerInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all